// --- DATA ARCHIVE ---
export const ALL_CASES = [
  {
    id: "01",
    slug: "anjel-chakma",
    name: "ANJEL CHAKMA",
    headline: "OUR BROTHER FROM THE NORTHEAST",
    tag: "UTTARAKHAND // HATE CRIME",
    authorityEmail: "sp-dehradun@uk.gov.in",
    summary: "He was one of us — a 24-year-old son of Bharat from Tripura, stabbed after racial slurs in Dehradun on December 9, 2025. He fought for 16 days before leaving us. The system delayed justice, but we will not forget our brother.",
    analysis: "This is not just a crime — it's an attack on every Indian from the Northeast. When they target one, they target all of us. Persistent discrimination cannot be tolerated in our Republic.",
    img: "https://static.toiimg.com/thumb/msid-126211451,width-1200,height-900,resizemode-4/126211451.jpg",
    bns_section: "BNS 103(1) (Murder), Potential SC/ST Act if applicable",
    newsLink: "https://timesofindia.indiatimes.com/india/im-indian-tripura-students-last-words-before-he-was-killed-in-a-racial-attack-protests-erupt-seeking-justice/articleshow/126209417.cms",
    featured: true
  },
  {
    id: "08",
    slug: "unnao-case",
    name: "UNNAO SURVIVOR",
    headline: "OUR DAUGHTER TARGETED BY POWER",
    tag: "UP // POLITICAL RAPE",
    authorityEmail: "home-up@nic.in",
    summary: "A minor daughter raped by an MLA in 2017. Her family attacked, father murdered in custody. She survived to fight — we fight with her.",
    analysis: "When politicians weaponize power against the weak, the Republic bleeds. She is our daughter. Her courage demands our action.",
    img: "https://static01.nyt.com/images/2012/12/30/world/sub30DELHIimage1/sub30DELHIimage1-articleLarge.jpg",
    bns_section: "BNS 103 (Murder), POCSO Act",
    newsLink: "https://en.wikipedia.org/wiki/2017_Unnao_rape_case",
    featured: false
  },
  {
    id: "04",
    slug: "ankita-bhandari",
    name: "ANKITA BHANDARI",
    headline: "OUR SISTER MURDERED FOR SAYING NO",
    tag: "UTTARAKHAND // ELITE CRIME",
    authorityEmail: "dm-pau@nic.in",
    summary: "19-year-old Ankita, our brave sister, refused 'special services' and paid with her life in 2022. The resort was demolished to hide evidence. She deserved protection — we all do.",
    analysis: "Power cannot silence dignity. When influential men destroy evidence, they destroy faith in justice. Ankita was family to us all.",
    img: "https://media.assettype.com/nationalherald%2F2022-10%2Ffe982ebd-2745-4b33-bb33-32b9fb34593e%2FAnkita_Bhandari_Resort.jpeg",
    bns_section: "BNS 103 (Murder), BNS 64 (Rape), BNS 238 (Evidence Destruction)",
    newsLink: "https://en.wikipedia.org/wiki/Murder_of_Ankita_Bhandari",
    featured: false
  },
  {
    id: "05",
    slug: "hathras-case",
    name: "HATHRAS VICTIM",
    headline: "OUR DALIT SISTER'S VOICE SILENCED",
    tag: "UP // CASTE ATROCITY",
    authorityEmail: "sp-hathras-up@nic.in",
    summary: "A young Dalit daughter of Bharat gang-raped and murdered in 2020. Police forcibly cremated her at midnight, denying her family closure. We stand with her forever.",
    analysis: "Caste violence backed by state power is betrayal of Ambedkar's dream. She was our sister — her pain is our pain, her fight is our fight.",
    img: "https://www.indexoncensorship.org/wp-content/uploads/2025/04/Girls-holding-candles-at-protest-scaled.jpg",
    bns_section: "SC/ST Act, BNS 64 (Rape), BNS 238 (Evidence Destruction)",
    newsLink: "https://en.wikipedia.org/wiki/2020_Hathras_gang_rape_and_murder",
    featured: false
  },
  {
    id: "06",
    slug: "manipur-women",
    name: "MANIPUR SISTERS",
    headline: "PARADED NAKED — OUR MOTHERS & DAUGHTERS",
    tag: "MANIPUR // ETHNIC VIOLENCE",
    authorityEmail: "dgp-manipur@nic.in",
    summary: "Kuki women — our sisters and mothers — paraded naked and assaulted in 2023 amid ethnic clashes. Their dignity stripped, but not their spirit. Justice delayed is justice denied.",
    analysis: "Sexual violence as a weapon in conflict shames the entire nation. These are our family members from Manipur. Silence is complicity.",
    img: "https://www.aljazeera.com/wp-content/uploads/2023/07/33PH9V7-highres-1689952680.jpg",
    bns_section: "BNS 74 (Outraging Modesty), BNS 103 (Murder)",
    newsLink: "https://www.bbc.com/news/world-asia-india-66253389",
    featured: false
  },
  {
    id: "07",
    slug: "delhi-hit-run",
    name: "ANJALI SINGH",
    headline: "OUR SISTER DRAGGED 12KM UNDER A CAR",
    tag: "DELHI // SYSTEMIC APATHY",
    authorityEmail: "cp.delhi@nic.in",
    summary: "Anjali, our sister, trapped and dragged for kilometers on New Year's 2023. Bystanders watched. The system failed her. We will not fail her memory.",
    analysis: "Apathy kills as surely as the crime. She could have been any of us — daughter, sister, friend. Society must wake up.",
    img: "https://th-i.thgim.com/public/incoming/653evw/article68237058.ece/alternates/FREE_1200/11908_31_5_2024_17_18_2_3_DSC_8345.JPG",
    bns_section: "BNS 103 (Murder), BNS 106 (Negligence)",
    newsLink: "https://en.wikipedia.org/wiki/Death_of_Anjali_Singh",
    featured: false
  },
];